### ISSUE TITLE
Cannot access database through Sequel Pro

### ISSUE THREAD

**Issue by adampmoss** [rgranadino/mage2_vagrant#51]
I seem to have a problem accessing the database with the box running. This is the error I get when trying to connect using Sequel Pro. Do you have any suggestions?

<img width="624" alt="screen shot 2015-12-02 at 16 52 12" src="https://cloud.githubusercontent.com/assets/4948435/11537504/350386c4-9915-11e5-9561-de9aaac682e4.png">

**Comment by bencorlett** [comment]
You might want to use the "SSH tunnel" option instead by providing the [SSH details](https://github.com/rgranadino/mage2_vagrant#ssh-info) and then the corresponding [MySQL details](https://github.com/rgranadino/mage2_vagrant#database-info).

Otherwise, you'll need to setup [port forwarding](https://docs.vagrantup.com/v2/networking/forwarded_ports.html) on the guest machine so that it's exposed by Vagrant. Honestly, I'd just SSH tunnel instead.

**Comment by rgranadino** [comment]
Agree with @bencorlett, SSH tunnel is the easiest route. Out of the box mysql is bound to 127.0.0.1 only.
You can use "vagrant" for both the SSH username and password:

<img width="468" alt="screen shot 2015-12-02 at 11 23 48 pm" src="https://cloud.githubusercontent.com/assets/327608/11554350/0935ef14-994c-11e5-90b9-ed75d6a2afd5.png">
